### ISSUE TITLE
How to build v8  for ARM V7 core without hardware FPU/VFP 

### ISSUE THREAD

**Issue by rench** [nodejs/node-v8#10]
* **Version**:Node.Js v6.10.0
* **Platform**: LEDE arm Linux 4.9.20
* **Subsystem**: arm Linux 4.9.20

i have a router with bcm4709 armv7 without hardware FPU for  lede/openwrt

i try many ways to build node.js and run in my router.
when i run node -v ,it works well.
but when i run other cmd invoke v8,will got Illegal instruction every times.

i know mips works well and must enable FPE.
but on arm linux ,the NWFPE is for OABI.for now ,all are EABI.
so ,if there someone can help me build v8 whitout vfp or make arm linux FPE work well.
thank you ! every one.

**Comment by targos** [comment]
@rench sorry for the late response. Can you please open your issue in the [help repository](https://github.com/nodejs/help/issues)?
This is a special repository that is automatically updated and the issue tracker is only used for issues with V8 upgrades.

**Comment by lezsakdomi** [comment]
Can you link the new issue please? :)
