### ISSUE TITLE
Windows build failure

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#102]
https://ci.nodejs.org/job/node-compile-windows/25607/label=win-vs2017/console

```
08:45:56   mksnapshot.cc
08:46:11      Creating library c:\workspace\node-compile-windows\Release\mksnapshot.lib and object c:\workspace\node-compile-windows\Release\mksnapshot.exp
08:46:20   mksnapshot.vcxproj -> c:\workspace\node-compile-windows\Release\\mksnapshot.exe
08:46:20   generating: "Release\obj\generate_snapshot\/embedded.S" "Release\obj\generate_snapshot\/snapshot.cc"
08:46:22   Assembling Release\obj\generate_snapshot\\embedded.S...
08:46:22 Release\obj\generate_snapshot\\embedded.S(1): error A2008: syntax error : / [c:\workspace\node-compile-windows\tools\v8_gypfiles\generate_snapshot.vcxproj]
```

**Comment by refack** [comment]
Seems like the generator doesn't handle `\` in paths:
```
.file 1 "....deps8srcuiltinsase.tq"
```
![image](https://user-images.githubusercontent.com/96947/55290740-ec8e4700-53a4-11e9-8e6a-c7cbcd4d868e.png)

![image](https://user-images.githubusercontent.com/96947/55290757-34ad6980-53a5-11e9-81e5-4912f7831b8c.png)

Where `\b` = `\0x08`

**Comment by refack** [comment]
https://github.com/nodejs/node-v8/blob/3c649ecee65eaf871dd8671896f84fea2e8da7c3/deps/v8/src/snapshot/embedded-file-writer.cc#L644
This doesn't work as expected (and BTW this is C++20)

Now that I think of it this is probably related to https://github.com/nodejs/node/pull/27017. This is a line from
`global_intermediate\torque-output-root\torque-generated\builtins-array-from-dsl-gen.cc`
```
    ca_.SetSourcePosition("..\..\deps\v8\src\builtins\array.tq", 20);
```

**Comment by refack** [comment]
Pushed a temporary patch as 42f8116d43cc002b98b3933c0af93b9fc3aad9b7
https://ci.nodejs.org/job/node-test-commit-node-v8/229/

**Comment by refack** [comment]
Ok, seems like we were missing another small thing 17d955fe13fa02eb57b46f352ffbc3c9947e6282

https://ci.nodejs.org/job/node-test-commit-windows-fanned/26076/

**Comment by refack** [comment]
Rebased 3c649ecee65eaf871dd8671896f84fea2e8da7c3...506610d5ae1aaeb69e5b82bd54095a9978533ace
Windows CI: https://ci.nodejs.org/job/node-test-commit-windows-fanned/26080/ ✔️
