### ISSUE TITLE
Last canaries lack binaries for some platforms

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-v8#105]
Last successful for Windows:
https://nodejs.org/download/v8-canary/v12.0.0-v8-canary201904031b435ddb85/

Lacking:
https://nodejs.org/download/v8-canary/v12.0.0-v8-canary20190405929ef2a396/
https://nodejs.org/download/v8-canary/v12.0.0-v8-canary20190406ed9cfb8555/
https://nodejs.org/download/v8-canary/v12.0.0-v8-canary201904072d523c2b09/

**Comment by refack** [comment]
Many other platforms are broken:
```
06:46:00 Completed iojs+release » osx1011-release-tar SUCCESS
06:46:00 Completed iojs+release » cross-compiler-armv7-gcc-4.9.4 SUCCESS
06:46:00 Completed iojs+release » rhel72-s390x-release FAILURE
06:53:01 Completed iojs+release » centos6-64-gcc6 SUCCESS
06:53:01 Completed iojs+release » vs2017-x86 FAILURE
06:53:01 Completed iojs+release » centos7-arm64-gcc6 FAILURE
07:51:22 Completed iojs+release » osx1011-release-pkg SUCCESS
07:51:22 Completed iojs+release » ppcle-ubuntu1404-release-64 FAILURE
07:51:22 Completed iojs+release » aix61-ppc64 FAILURE
07:51:22 Completed iojs+release » vs2017-x64 FAILURE
07:51:22 Completed iojs+release » smartos17-release SUCCESS
07:51:22 Completed iojs+release » cross-compiler-armv6-gcc-4.9.4 SUCCESS
```
Some seem like actual V8 code issues
https://gist.github.com/refack/9ec1797d4da8df4590a0086bb22f1c8a

**Comment by refack** [comment]
Last couple of days we are back to full repertoire
https://nodejs.org/download/v8-canary/v13.0.0-v8-canary201906016be26d0c21/
