### ISSUE TITLE
V8 7.5 - Compilation issues on multiple platforms

### ISSUE THREAD

**Issue by refack** [nodejs/node-v8#107]
Refs: list of patches needed to get V8 7.5 to compile in MSVS on Windows https://github.com/nodejs/node-v8/commits/v8-7.5

Seems like there are a few code issues in [`7.5.288.2`](https://github.com/nodejs/node-v8/commit/2fef4d2f22b9f42042dcd96374e01dfc736bd782)
1. Access RIP register from thread context fails to compile on Windows/ia32, LinuxONE, CentOS7/ppcle, possibly others.
   * Windows can't compile without this kludge https://github.com/nodejs/node-v8/blob/b174edcd3298737b4c524a376188a8b879310734/deps/v8/src/trap-handler/handler-inside-win.cc#L93-L95
   * Several [other POSIX fail](https://ci.nodejs.org/job/node-test-commit/28491/) with stuff around:
   ```
   13:17:26 ../deps/v8/src/trap-handler/handler-inside-posix.cc: In function ‘bool v8::internal::trap_handler::TryHandleSignal(int, siginfo_t*, void*)’:
   13:17:26 ../deps/v8/src/trap-handler/handler-inside-posix.cc:112:42: error: ‘struct mcontext_t’ has no member named ‘gregs’; did you mean ‘regs’?
   13:17:26      auto* context_rip = &uc->uc_mcontext.gregs[REG_RIP];
   13:17:26                                           ^~~~~
   13:17:26 ../deps/v8/src/trap-handler/handler-inside-posix.cc:112:48: error: ‘REG_RIP’ was not declared in this scope
   13:17:26      auto* context_rip = &uc->uc_mcontext.gregs[REG_RIP];
   13:17:26                                                 ^~~~~~~
   ```
2. missing methods on MSVS:
   * https://github.com/nodejs/node-v8/commit/952f4c836abe26b62b9d557e12ee8cb2ed1c9d2f
   * https://github.com/nodejs/node-v8/commit/209e8d7e9f9dbeda63d60c1ca93163c19e4187c8
3. missing includes (fails to compile because of missing symbols of inline methods):
   * https://github.com/nodejs/node-v8/commit/d02bed8603b1bc0a8f85343e51442d7cb3977bc7
4. Higher `_WIN32_WINNT` required to access `Rtl*GrowableFunctionTable` symbols (https://github.com/nodejs/node-v8/commit/6df37335ea02e61df7c9284b4ca81fcb90a09e4d), otherwise `deps/v8/src/unwinding-info-win64.cc` fails to compile.
   * [`RtlAddGrowableFunctionTable`](https://docs.microsoft.com/en-us/windows/desktop/api/winnt/nf-winnt-rtladdgrowablefunctiontable) supported only from Windows 8, Node.js wants to support Windows 7 until official EoL in 1.1.2020.
![image](https://user-images.githubusercontent.com/96947/57545492-7d532d80-7328-11e9-9a52-2eab8ca2cc07.png)

Ping @hashseed, any advice?

/CC @nodejs/v8-update @nodejs/platform-windows

**Comment by hashseed** [comment]
@schuay @ahaas does this ring bells?

**Comment by schuay** [comment]
> missing includes (fails to compile because of missing symbols of inline methods): d02bed8

What are the missing symbols? Ideally we would avoid an `objects-inl.h` include in the snapshot file. As a shot in the dark, I suspect the include should be added in `src/snapshot/snapshot.h` instead, or wherever the missing symbols are used.

> Higher _WIN32_WINNT required to access Rtl*GrowableFunctionTable symbols (6df3733), otherwise deps/v8/src/unwinding-info-win64.cc fails to compile.

Could you open a bug at [crbug.com/v8/new](crbug.com/v8/new) with more details? AFAIK these functions *are* only used if `::IsWindows8OrGreater()` returns true. Is the problem that the type definitions are not available?

**Comment by mhdawson** [comment]
@john-yan @midladfarca can you take look at the issues on linuxone/centos7/ppcle

**Comment by john-yan** [comment]
Is there a CI link that I can take a look at?

**Comment by refack** [comment]
https://ci.nodejs.org/job/node-test-commit/28626/
specifically:
LinuxONE - https://ci.nodejs.org/job/node-test-commit-linuxone/13350/nodes=rhel72-s390x/
CentOS7/PPC64 - https://ci.nodejs.org/job/node-test-commit-plinux/25808/nodes=centos7-ppcle/
AIX - https://ci.nodejs.org/job/node-test-commit-aix/23190/nodes=aix61-ppc64/

**Comment by miladfarca** [comment]
Some of the Macros defined under `src/libsampler/sampler.cc`, to make `ucontext->uc_mcontext` host specific,  might have to be ported. We will investigate.

**Comment by miladfarca** [comment]
Looking at `BUILD.gn` under `V8`, `"src/trap-handler/handler-inside-posix.cc",` is only being used when running on `v8_current_cpu == "x64"`. Same need to be implemented on Nodejs GYP, to only include the file when compiling on x64.

**Comment by refack** [comment]
> Looking at `BUILD.gn` under `V8`, `"src/trap-handler/handler-inside-posix.cc",` is only being used when running on `v8_current_cpu == "x64"`.

Oops, seems like I missed the indentation level in https://github.com/nodejs/node-v8/blob/b174edcd3298737b4c524a376188a8b879310734/deps/v8/BUILD.gn#L2951-L2984
Thanks, @miladfarca for the heads up.

**Comment by refack** [comment]
CI passes for LinuxONE and CentOS7/PPC64 - https://ci.nodejs.org/job/node-test-commit/28645/ with latest https://github.com/nodejs/node-v8/commits/v8-7.5
AIX fails with `libv8_compiler_for_mksnapshot.a: not a COFF file`.

**Comment by miladfarca** [comment]
@refack 
`v8_gypfiles/v8.gyp`, line 890:
```
      'target_name': 'v8_compiler_for_mksnapshot',
      'type': 'static_library',
      'dependencies': [
```
Shouldn't the type be 'none'? as this isn't marked as a static library in `BUILD.gn` and has no sources.

**Comment by refack** [comment]
> Shouldn't the type be `none`?

Makes sense. I've pushed a test in https://github.com/nodejs/node/commit/c10a83ed50da982503973ac3f64166d8796c5192.
(BTW: I'm working on adding a target types to GYP3 that are similar to GN's `group` and `config`)

**Comment by refack** [comment]
Update: most MSVC issues are triggered by setting `BUILDING_V8_SHARED`, which defines
https://github.com/nodejs/node-v8/blob/3fc3d9a8f17f1806ab9ee306c1db1ebd7a46e480/deps/v8/src/base/macros.h#L418
and `__declspec(dllexport)` forces the linker to look for instantiations of all templated methods.

We've unset it for now https://github.com/nodejs/node-v8/commit/379835a903da6660669c3e9f90c3d5f145bf3785#diff-3c97d28212ec6ec5600be248eb430994R326
but issue still exists if building `v8.dll`

(`_WIN32_WINNT` bump still required, otherwise `Rtl*GrowableFunctionTable` symbols are not defined)

**Comment by mhdawson** [comment]
@miladfarca, @john-yan @gireeshpunathil can you help look at the AIX issue

**Comment by miladfarca** [comment]
@mhdawson @refack is AIX having other problems? seems like the suggestions in the last comment fixes the issue?

**Comment by mhdawson** [comment]
@miladfarca ok thanks, that was not clear to me when I scanned the issue. Thanks for clarifying.

**Comment by refack** [comment]
I'm going to close this issue since 75 has moved to https://github.com/nodejs/node/pull/27375 and we resolved most issues that we hit originally.

Thank you everyone for helping 🎩

**Comment by refack** [comment]
Refs: https://bugs.chromium.org/p/v8/issues/detail?id=9295 -  `v8_win64_unwinding_info` makes process hang on abort
