### ISSUE TITLE
V8 files moving

### ISSUE THREAD

**Issue by hashseed** [nodejs/node-v8#108]
Please be advised that due to slight changes to V8's code review guidelines, we need to move some source files. That may break the gyp build.

https://groups.google.com/forum/?#!topic/v8-dev/b3ELZa4JPss

**Comment by refack** [comment]
Thank you very much for the heads up! It indeed cough us mid-sync trying to get the v8-canary back to life...
Anyway we got the gypfiles a tiny bit more robust with: https://github.com/nodejs/node-v8/blob/7c86ec79a731b0643477390a776e561b903c9cda/tools/v8_gypfiles/v8.gyp#L319

So if you remember to ping us on `BUILD.gn` structure changes that require changing the scraping regex, that would be awesome-sauce.

**Comment by refack** [comment]
P.S. the canary is feeling slightly better https://nodejs.org/download/v8-canary/v13.0.0-v8-canary201905227c86ec79a7/
