### ISSUE TITLE
known: canary is broken

### ISSUE THREAD

**Issue by refack** [nodejs/node-v8#109]
At least two issues:
- [ ] https://github.com/nodejs/node/commit/485a39b5d455692682d20786612a8c50944302fe doesn't float
- [ ] https://github.com/v8/v8/commit/437f680e19b50ce2c608fab1ecfe0be03bf28440 needs migrating

IIUC @ryzokuken is on it.

**Comment by ryzokuken** [comment]
Done! 😄
