### ISSUE TITLE
Whitespace issue on BUILD.gn

### ISSUE THREAD

**Issue by ryzokuken** [nodejs/node-v8#113]
There's an inconsistent whitespace symbol in BUILD.gn (https://github.com/v8/v8/blob/master/BUILD.gn#L94) that breaks `./configure` for Node. We've patched gyp internally to handle it, but it looks like a mistake and it should be patched to avoid similar issues.

/cc @hashseed I'll make a CL.

**Comment by ryzokuken** [comment]
Fixed in https://crrev.com/8ab0eed20cb9336420937c016e3821ea7ef28985

**Comment by targos** [comment]
Nice, thanks!
