### ISSUE TITLE
Node broken if v8_enable_31bit_smis_on_64bit_arch is on

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#116]
Following an upstream change, we tried to turn `v8_enable_31bit_smis_on_64bit_arch` on by default

The binary is broken in mysterious ways.

- `./node script.js` hangs without using any CPU.
  - `kill -s SIGUSR1 pid` makes it crash:
![image](https://user-images.githubusercontent.com/2352663/65947848-63ca9380-e439-11e9-8754-8c3d393cc14a.png)
- `node inspect script.js` crashes:
![image](https://user-images.githubusercontent.com/2352663/65947875-6dec9200-e439-11e9-9743-d52142858bce.png)

**Comment by targos** [comment]
Upstream change: https://github.com/v8/v8/commit/d68bf369cb8f2cdd2068dd8c31c2418b2b974c60

**Comment by targos** [comment]
I pushed https://github.com/nodejs/node/commit/362d16c6a3809be62d53eb1a3c8333bb1784f373 to disable it for now.

**Comment by addaleax** [comment]
This is caused by an ABI mismatch between our build of V8 and the Node.js parts of the source; the `V8_31BIT_SMIS_ON_64BIT_ARCH` define needs to be set for both V8 and Node.js (and for addons) if the feature is enabled. On `canary/canary`, it is only set for V8.

**Comment by targos** [comment]
is it a mistake we made when porting the flag to GYP or the same issue would happen with GN ?

**Comment by addaleax** [comment]
If that’s a question directed at me – I really don’t know, sorry. The flag is a bit different from the other V8 flags, so it’s quite possible that this happened while porting the flag over. And either way, this seems like something that needs to be fixed in GYP; but:

I also remember there being a larger conversation about ABI compatibility and pointer compression. I think this flag needs to go into `common.gypi`, because it affects the addon ABI. That also means we can’t change it during a Node.js release line unless we come up with something clever.

**Comment by targos** [comment]
Yeah, so defining `V8_31BIT_SMIS_ON_64BIT_ARCH` explicitly in `common.gypi` fixes it. Is it because the macro is used in V8's headers?

**Comment by addaleax** [comment]
> Is it because the macro is used in V8's headers?

Yes, and because it doesn’t define a feature, but rather a format that V8 and its consumer have to agree on (namely how to pass integers through the API from and to V8).

**Comment by richardlau** [comment]
Does this flag have implications for n-api (i.e. existing addons wouldn't work on builds with this defined?

**Comment by addaleax** [comment]
@richardlau No, N-API is unaffected because that’s a fully separate ABI.

**Comment by isheludko** [comment]
It looks like these two CLs were not merged to Node:
https://github.com/v8/node/commit/7dffdf0ac3a4c8d7e0b8a29f597756b02b2f43a2
https://github.com/v8/node/commit/a044ce1c5fc26f24f5011758b217283109b2601f

**Comment by targos** [comment]
I added the variables and macros to `common.gypi` in https://github.com/nodejs/node/commit/048918afe31d03149e690182197cda91aa9964d2
