### ISSUE TITLE
Last canaries lack Windows binaries

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-v8#117]
The last Windows build is [of 2019.09.12](https://nodejs.org/download/v8-canary/v13.0.0-v8-canary201909122854701dc7/).

**Comment by ryzokuken** [comment]
@targos

**Comment by targos** [comment]
Error:

```
12:10:28 c:\ws\deps\v8\src\codegen\turbo-assembler.h(105): fatal error C1017: invalid integer constant expression (compiling source file ..\..\deps\v8\src\codegen\x64\assembler-x64.cc) [c:\ws\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
```

**Comment by targos** [comment]
Also: https://github.com/nodejs/node-v8/issues/118#issuecomment-540535900

**Comment by vsemozhetbyt** [comment]
Seems fixed in today build: https://nodejs.org/download/v8-canary/v13.0.0-v8-canary20191022e5d3472f57/
