### ISSUE TITLE
Failing test: test-assert

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#122]
```
=== release test-assert ===
Path: parallel/test-assert
/home/mzasso/git/nodejs/canary/test/common/index.js:621
        throw new assert.AssertionError({
        ^

AssertionError [ERR_ASSERTION]: Expected "actual" to be reference-equal to "expected":
+ actual - expected

  Comparison {
    code: 'ERR_ASSERTION',
+   message: 'false == true',
-   message: 'The expression evaluated to a falsy value:\n\n  assert(1 === 2)\n',
    type: [Function: AssertionError]
  }
    at new AssertionError (internal/assert/assertion_error.js:424:11)
    at Object.innerFn (/home/mzasso/git/nodejs/canary/test/common/index.js:621:15)
    at expectedException (assert.js:650:26)
    at expectsError (assert.js:775:3)
    at Function.throws (assert.js:824:3)
    at Object.expectsError (/home/mzasso/git/nodejs/canary/test/common/index.js:633:12)
    at Object.<anonymous> (/home/mzasso/git/nodejs/canary/test/parallel/test-assert.js:913:8)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1224:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: [AssertionError],
  expected: [Object],
  operator: 'common.expectsError'
}
Command: out/Release/node --expose-internals /home/mzasso/git/nodejs/canary/test/parallel/test-assert.js
```

**Comment by BridgeAR** [comment]
Just a guess: I believe the V8 team considered removing `stackframe.getFunction()`. That function is necessary for this test to pass.

**Comment by targos** [comment]
`getFunction` still returns a function. The problem seems to be that it returns a reference to the `assert.ok` function instead of the function being tested (created with `new Function()`)

**Comment by targos** [comment]
This is where it fails:

https://github.com/nodejs/node-v8/blob/35eb0577120e3353dc652a59801850dd56b62649/test/parallel/test-assert.js#L912-L920

**Comment by BridgeAR** [comment]
> The problem seems to be that it returns a reference to the assert.ok function instead of the function being tested

That sounds like a breaking change? I guess it could also something that was not intentional and regressed?

**Comment by ryzokuken** [comment]
@targos I guess it makes sense to open an issue on the V8 issue tracker?

**Comment by targos** [comment]
@ryzokuken sure, would you like to do it? Best would be to have a repro using d8.

**Comment by ryzokuken** [comment]
@targos on it.

**Comment by targos** [comment]
Actually the solution is to revert https://github.com/nodejs/node/commit/5981fb7faa13de95550b01272ebfbd8a5220aadb
