### ISSUE TITLE
Build broken on SmartOS

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#125]
https://ci.nodejs.org/job/node-test-commit-smartos/29426/nodes=smartos18-64/console

```
11:42:50 dtrace: failed to compile script src/v8ustack.d: line 414: failed to resolve V8DBG_CLASS_CONSSTRING__FIRST_OFFSET__INT: Unknown variable name
```

/cc @nodejs/platform-smartos

**Comment by cjihrig** [comment]
I'll take a look at this, but it might be a few days. I'm currently sick, plus I have a few other things going on ATM.

**Comment by targos** [comment]
No problem, thanks!

**Comment by cjihrig** [comment]
@targos can you try https://github.com/cjihrig/node-v8/commit/ce607e4f83dbdd09c06b4d2370d1a6add3563d8e, https://github.com/cjihrig/node-v8/commit/cfd61037745fc96a1f4908077377795a2c87a53d, and https://github.com/cjihrig/node-v8/commit/4177a696c4a2699b16a1033837a989f853cbc139. Only the third commit is SmartOS specific. The first two are about postmortem metadata, which should be broken on all platforms.

**Comment by targos** [comment]
@cjihrig thanks, I applied your commits.

Now it errors with: `16:00:19 dtrace: failed to compile script src/v8ustack.d: line 414: failed to resolve V8DBG_CLASS_CONSSTRING__FIRST_STRING: Unknown variable name`.
Maybe V8 changed it already in the mean time?

**Comment by targos** [comment]
Ping @cjihrig

**Comment by cjihrig** [comment]
I'm working on setting up a new SmartOS instance to test on. I haven't forgotten about this.

**Comment by cjihrig** [comment]
@targos, looking at this again, I think the constants in  https://github.com/cjihrig/node-v8/commit/4177a696c4a2699b16a1033837a989f853cbc139 are just missing an extra `_`. I think https://github.com/cjihrig/node-v8/commit/d677605bfb79c016cae863f4dd8f2cd8936d8715 should do the trick instead.

**Comment by cjihrig** [comment]
Also, unrelated to this issue, but related to updating V8, have you seen https://github.com/nodejs/node/issues/30916#issuecomment-565743054? I don't think that issue can be addressed in the main repo yet.

**Comment by targos** [comment]
Applied fix to canary. Thank you!
