### ISSUE TITLE
zlib build fail on windows platform

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-v8#139]
```console
C:\projects\appveyor-playground\node-v8\deps\v8\third_party\zlib\cpu_features.c(45,1): fatal error C1189: #error:  cpu_features.c CPU feature detection in not defined for your platform 
```

**Comment by gengjiawen** [comment]
cc @nodejs/platform-windows @mscdex

**Comment by seishun** [comment]
It seems after [this change](https://chromium.googlesource.com/chromium/src/third_party/zlib/+/ee4f17204f61e39851f833199965e72a76e5437f%5E%21/#F4) zlib requires the X86_WINDOWS define to be set on Windows.

**Comment by gengjiawen** [comment]
close via https://github.com/nodejs/node-v8/pull/141.
