### ISSUE TITLE
Update canary-base to remove stale commits

### ISSUE THREAD

**Issue by mmarchini** [nodejs/node-v8#148]
* https://github.com/nodejs/node/commit/7d6911eb31f61551a08124e43db2ad3fb1a177d0 is a no-op now due to postmortem changes upstream (other postmortem commits are probably stale as well)
* https://github.com/nodejs/node/commit/644a85db2fa0b05b288a92b8ac8d95432bcaf0e5 and https://github.com/nodejs/node/commit/5f693ef7ffbf9a50bc5d4bc45167adc6df60e5a0 should be squashed together

What's the process to update canary-base? Should I just force-push there, or is there a better way?

**Comment by targos** [comment]
Force push is the way

**Comment by mmarchini** [comment]
Ok, will do tomorrow :)

**Comment by gengjiawen** [comment]
> Force push is the way

Not sure code merge strategy in this repo. Can you merge https://github.com/nodejs/node-v8/pull/147 before force update ? @targos

**Comment by mmarchini** [comment]
Will update canary-base tomorrow, it's late and I'll probably make a mistake if I rebase it now.

**Comment by mmarchini** [comment]
In the end I didn't rebase it today because there was still some legitimate failures on the PR (and I wanted to avoid rebasing multiple times). I think now things are more stable (let's see the results from the last CI), so tomorrow I'll do it.

**Comment by mmarchini** [comment]
Rebased and force-pushed. I couldn't cherry-pick #147 (conflict, will cherry-pick next week) and #149 (failing test). I cherry-picked #150, otherwise canary-base wouldn't build.
