### ISSUE TITLE
No Windows builds since 2020.05.28

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-v8#158]
https://nodejs.org/download/v8-canary/v15.0.0-v8-canary2020053077f9337a58/
https://nodejs.org/download/v8-canary/v15.0.0-v8-canary202005311fd149cdf5/
https://nodejs.org/download/v8-canary/v15.0.0-v8-canary20200601bbef71d2b9/
https://nodejs.org/download/v8-canary/v15.0.0-v8-canary202006025eea8ef984/

**Comment by bzoz** [comment]
Maybe it is because the build issues in https://github.com/nodejs/node/pull/33579?

**Comment by vsemozhetbyt** [comment]
FWIW, the recent nightly builds have Windows binaries:

https://nodejs.org/download/nightly/v15.0.0-nightly202005296a1df3b5af/
https://nodejs.org/download/nightly/v15.0.0-nightly20200530d79c330186/
https://nodejs.org/download/nightly/v15.0.0-nightly202005312935f72ae1/

**Comment by gengjiawen** [comment]
> Maybe it is because the build issues in [nodejs/node#33579](https://github.com/nodejs/node/pull/33579)?

Is it the node-v8 daily windows build using vs2017 ? @targos @ryzokuken

**Comment by gengjiawen** [comment]
Looks like windows build is broken: https://github.com/nodejs/node-v8/runs/726470134.

**Comment by gengjiawen** [comment]
> Looks like windows build is broken: [nodejs/node-v8/runs/726470134](https://github.com/nodejs/node-v8/runs/726470134).
> 
> ```
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\memory(1757,1): error C2027: use of undefined type 'v8::internal::OffThreadTransferHandleStorage' [D:\a\node-v8\node-v8\tools\v8_gypfiles\v8_init.vcxproj]
> D:\a\node-v8\node-v8\deps\v8\src\execution\off-thread-isolate.h(20): message : see declaration of 'v8::internal::OffThreadTransferHandleStorage' [D:\a\node-v8\node-v8\tools\v8_gypfiles\v8_init.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\memory(1756): message : while compiling class template member function 'void std::default_delete<v8::internal::OffThreadTransferHandleStorage>::operator ()(_Ty *) noexcept const' [D:\a\node-v8\node-v8\tools\v8_gypfiles\v8_init.vcxproj]
>           with
>           [
>               _Ty=v8::internal::OffThreadTransferHandleStorage
>           ]
> ```

Not sure related to this: 
https://github.com/nodejs/node/pull/33685
https://github.com/v8/v8/commit/e87972b162c43ae7bd185f0042e65dcb61940a26#commitcomment-39582496.

**Comment by gengjiawen** [comment]
Possible fix: https://github.com/nodejs/node-v8/pull/159

**Comment by gengjiawen** [comment]
> Possible fix: #159

Looks like build passed on github action, upstream patch: https://chromium-review.googlesource.com/c/v8/v8/+/2226121.

**Comment by gengjiawen** [comment]
Looks like fixed: https://nodejs.org/download/v8-canary/v15.0.0-v8-canary20200603908772e6f4/
