### ISSUE TITLE
N-API test failure

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#173]
https://ci.nodejs.org/job/node-test-commit-linux/37061/nodes=ubuntu1804-64/console

```
10:35:08 not ok 2879 js-native-api/test_object/test
10:35:08   ---
10:35:08   duration_ms: 0.330
10:35:08   severity: crashed
10:35:08   exitcode: -11
10:35:08   stack: |-
10:35:08   ...
```

**Comment by mhdawson** [comment]
Related test: https://github.com/nodejs/node/tree/master/test/js-native-api/test_object

**Comment by targos** [comment]
I cannot reproduce on my system (CentOS 8, with GCC 8.3.1)

**Comment by mhdawson** [comment]
This did not reproduce on my system either (Ubuntu 18.04.4, GCC 7.5.0)

**Comment by mhdawson** [comment]
I think one of the machines in the build matched the ubuntu/gcc level that I have: 

```text
03:11:46 Detected C++ compiler (CXX=ccache g++) version: 7.5.0
03:11:46 Detected C compiler (CC=ccache gcc) version: 7.5.0
```
from https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu1804-64/37061/consoleFull

So maybe we should re-run after the security release to see if it re-occurs

**Comment by targos** [comment]
It's been occuring for some time (I haven't checked when it started to fail). Here's an other example from one week ago: https://ci.nodejs.org/view/MyJobs/job/node-test-commit-node-v8/600/

**Comment by mhdawson** [comment]
So its intermittent or fails every time in the CI ?

**Comment by mhdawson** [comment]
Also to confirm, the job just checks out the canary branch (the default) of node-v8 and does make test ?

**Comment by targos** [comment]
It fails every time in CI. History: https://ci.nodejs.org/view/MyJobs/job/node-test-commit-node-v8/
The job triggers a `node-test-commit` subjob with the `canary` branch of `nodejs/node-v8`

**Comment by mhdawson** [comment]
Strange since that should match what we've run.  I wonder if it would make sense to clear the workspace and make sure it recreates.

**Comment by mhdawson** [comment]
@targos are you ok if we clear the workspace to see if that makes any difference?

**Comment by targos** [comment]
I'm ok

**Comment by mhdawson** [comment]
Ok, have cleared the workspace for https://ci.nodejs.org/job/node-test-commit-node-v8/.  We'll see if that makes any difference.

**Comment by gabrielschulhof** [comment]
I can't reproduce this.

**Comment by gabrielschulhof** [comment]
Looks like Ubuntu 16.04 64-bit with gcc-7.5.0.

**Comment by mhdawson** [comment]
Using test-joyent-ubuntu1804-x64-1 on which we saw the failure recently to investigate

**Comment by mhdawson** [comment]
Compiling in directory: https://github.com/nodejs/node-v8.git

**Comment by mhdawson** [comment]
did not recreate with a `make node` followed by `make test`, so likely means that its related to config set by the CI job, for example compiler or something else

**Comment by mhdawson** [comment]
Called set-compiler but not the ccache config still did not recreate, but not much seemed to be compiled either. Having said that it did not seem to have changed the compiler either

**Comment by mhdawson** [comment]
Double check last failure was on https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu1804-64/37204/

**Comment by mhdawson** [comment]
Remaining thing that is not like ci would be the ccache.  Next week I'll create a duplicate job that would only run on the same machine and validate it fails under CI, and if so then try to remove the part of the job which configures ccache.

**Comment by mhdawson** [comment]
Create this job: https://ci.nodejs.org/job/node-test-commit-linux-mhdawson/ as clone of main job which only runs on test-joyent-ubuntu1804-x64-1 and uses node-v8 and the canary branch.

Run to see if it recreates: https://ci.nodejs.org/job/node-test-commit-linux-mhdawson/2/console

**Comment by mhdawson** [comment]
Unfortunately that job is not working, need to look further

**Comment by mhdawson** [comment]
Recreated job as https://ci.nodejs.org/job/node-test-commit-linux-mhdawson/, does not default to node-v8/canary, but seems to be running having specified that in the build parameters

**Comment by mhdawson** [comment]
Tried recreating through a clone of the job. Tried the follwing:

1) run the job specifying node-v8/canary - no recreate
2) first run the job for node/master, followed with run for node-v8/canary to more closely match what we see in the community runs - no recreate

**Comment by mhdawson** [comment]
Looking at the build jobs they look pretty much the same. The only thing I can see is that my new job does not have the `NODE_MAJOR_VERSION` and `IGNORE_FLAKY_TESTS ` parameters defined.  I've added those and kicked off another run

**Comment by mhdawson** [comment]
Still no recreate, the only other thing I can think of trying is to clear the workspace for node-test-commit-linux but that would definitely have an impact on the next run.

**Comment by mhdawson** [comment]
Wiping workspace for `node-test-commit-linux`

**Comment by mhdawson** [comment]
node-v8 run to see if wiping workspace had any effect: https://ci.nodejs.org/view/All/job/node-test-commit-node-v8/622/

**Comment by mhdawson** [comment]
second run as first one seems to fail, missing some config after workspace clean https://ci.nodejs.org/job/node-test-commit-node-v8/623/

**Comment by mhdawson** [comment]
And again https://ci.nodejs.org/job/node-test-commit-node-v8/624/

**Comment by mhdawson** [comment]
Seems like you have to run 3 times after workspace clear, third one now seems to be building now.

**Comment by mhdawson** [comment]
Looks to me like the linux job on ubuntu 1804 passed in this run: https://ci.nodejs.org/job/node-test-commit-node-v8/624/

**Comment by mhdawson** [comment]
Lets see if it passes in the next regularly scheduled canary builds, if so it seems like the workspace clean removed whatever was causing the problem.

**Comment by targos** [comment]
Thanks for looking into it @mhdawson ! Here is today's run: https://ci.nodejs.org/view/MyJobs/job/node-test-commit-node-v8/626/

**Comment by mhdawson** [comment]
@targos that link seems to 404 for me. Launched this one https://ci.nodejs.org/view/MyJobs/job/node-test-commit-node-v8/628/

**Comment by mhdawson** [comment]
Ok test_object passed in the last build I started as well. @targos I'm going to close this as I think it's resolved. Please re-open if it recreates.
