### ISSUE TITLE
drop commit no longer needed.

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-v8#176]
![image](https://user-images.githubusercontent.com/3759816/93543461-39495180-f98e-11ea-807a-251a6f1aa1af.png)

**Comment by targos** [comment]
Why are they no longer needed?

**Comment by gengjiawen** [comment]
Aa for as I know, now minimum build Xcode is 10 and Visual Studio is 2019.

**Comment by targos** [comment]
I don't know about Xcode, but I know that we needed to keep the VS2015 patch to support building native addons.

@joaocgreis is that still going to be the case with Node.js 15 ?

**Comment by targos** [comment]
@gengjiawen If you would like to push for it, please try to open a PR in nodejs/node that reverts them. We'll see if CI is happy or not.
