### ISSUE TITLE
Use VS2019 to compile V8 latest source code error function redefinition

### ISSUE THREAD

**Issue by sleikang** [nodejs/node-v8#177]
VS2019 is_clang=false Error
Use VS2019 to compile V8 latest source code error function redefinition

C:/Users/leixiaojun/Downloads/sdk/depot_tools/bootstrap-3_8_0_chromium_8_bin/python/bin/python.exe ../../build/toolchain/win/tool_wrapper.py link-wrapper environment.x64 False link.exe /nologo /OUT:./mksnapshot.exe /PDB:./mksnapshot.exe.pdb @./mksnapshot.exe.rsp
1>v8_libbase.dll.lib(v8_libbase.dll) : error LNK2005: "public: bool __cdecl v8::base::time_internal::TimeBase::IsNull(void)const " (?IsNull@?$TimeBase@VTimeTicks@base@v8@@@time_internal@base@v8@@QEBA_NXZ) 已经在 setup-isolate-full.obj 中定义
1>
1>
1>v8_libbase.dll.lib(v8_libbase.dll) : error LNK2005: "public: class v8::base::TimeDelta __cdecl v8::base::time_internal::TimeBase::operator-(class v8::base::TimeTicks)const " (??G?$TimeBase@VTimeTicks@base@v8@@@time_internal@base@v8@@qeba?AVTimeDelta@23@VTimeTicks@23@@z) 已经在 setup-isolate-full.obj 中定义
1>
1>
1>v8_libbase.dll.lib(v8_libbase.dll) : error LNK2005: "public: __cdecl v8::base::TimeTicks::TimeTicks(void)" (??0TimeTicks@base@v8@@QEAA@XZ) 已经在 setup-isolate-full.obj 中定义
1>
1>
1>v8_libbase.dll.lib(v8_libbase.dll) : error LNK2005: "public: static void * __cdecl v8::base::Thread::GetExistingThreadLocal(int)" (?GetExistingThreadLocal@Thread@base@v8@@SAPEAXH@Z) 已经在 setup-isolate-full.obj 中定义
1>
1>
1>v8_libbase.dll.lib(v8_libbase.dll) : error LNK2005: "public: static class v8::base::TimeDelta __cdecl v8::base::TimeDelta::FromMicroseconds(__int64)" (?FromMicroseconds@TimeDelta@base@v8@@sa?AV123@_J@Z) 已经在 setup-isolate-full.obj 中定义
1>
1>
1> 正在创建库 .\mksnapshot.lib 和对象 .\mksnapshot.exp
1>
1>
1>.\mksnapshot.exe : fatal error LNK1169: 找到一个或多个多重定义的符号

**Comment by targos** [comment]
This project is not about compiling V8 directly with depot_tools but embedding it in Node.js.
