### ISSUE TITLE
V8 CI broken by test runner changes

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#180]
See https://ci.nodejs.org/job/node-test-commit-v8-linux/3479/nodes=benchmark-ubuntu1604-intel-64,v8test=v8test/console

Error:
```
11:14:22 deps/v8/tools/run-tests.py --gn --arch=x64 \
11:14:22 			--mode=release --progress=dots --timeout=120 \
11:14:22 			mjsunit cctest debugger inspector message preparser \
11:14:22 			--junitout /home/iojs/build/workspace/node-test-commit-v8-linux/nodes/benchmark-ubuntu1604-intel-64/v8test/v8test/v8-tap.xml
11:14:22 Usage: run-tests.py [options] [tests]
11:14:22 
11:14:22 run-tests.py: error: no such option: --mode
```

/cc @nodejs/build

**Comment by Trott** [comment]
Here's the relevant bit of script:

```sh
# we run the `v8-updates` suite on machines labeled `*benchmark*`
case "$nodes" in 
  *benchmark*)
    NODE_TEST_DIR=/home/iojs/node-tmp NODE_COMMON_PORT=15000 python tools/test.py -j $JOBS -p tap --mode=release --flaky-tests=run v8-updates
    # Flag test as unstable if `perf` is not found
    perf --version || exit 54
  ;;
esac
```

I can remove the `--mode=release` if we're pretty sure that's all that needs to happen and this is time sensitive or anything.

**Comment by richardlau** [comment]
Will 

> Here's the relevant bit of script:
> 
> ```shell
> # we run the `v8-updates` suite on machines labeled `*benchmark*`
> case "$nodes" in 
>   *benchmark*)
>     NODE_TEST_DIR=/home/iojs/node-tmp NODE_COMMON_PORT=15000 python tools/test.py -j $JOBS -p tap --mode=release --flaky-tests=run v8-updates
>     # Flag test as unstable if `perf` is not found
>     perf --version || exit 54
>   ;;
> esac
> ```
> 
> I can remove the `--mode=release` if we're pretty sure that's all that needs to happen and this is time sensitive or anything.

Isn’t that supposed to run our test runner and not V8’s?

**Comment by richardlau** [comment]
@targos The job runs the `test-v8` target and this is invoking the V8 test runner:
https://github.com/nodejs/node/blob/6141ca318ad52c507fd9fbc49218768b72eb8f54/Makefile#L670-L676
so this should be fixed in the canary branch.

**Comment by targos** [comment]
Thanks @richardlau. This already affects V8 8.7. I added a commit to remove the flag in https://github.com/nodejs/node/pull/35700

**Comment by richardlau** [comment]
@targos It looks like V8 8.6 was also affected -- the V8 CI for Node.js 15 (https://github.com/nodejs/node/pull/35014#issuecomment-711478666) failed.
cc @BethGriggs

**Comment by targos** [comment]
Okay, sorry about that. It passed originally: https://ci.nodejs.org/job/node-test-commit-v8-linux/3416/ but I guess they backported the test runner changes.

Let me open a PR against master.
