### ISSUE TITLE
V8 tools were migrated to ESM

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#182]
See https://github.com/v8/v8/commit/94bce1dcaca3b42bbdca5ca8d3ca81abfcbc245b and https://github.com/v8/node/commit/1dae89124aa1be5262357496483c98ee74a2a3e1

We'll need to change how we load them.

**Comment by devsnek** [comment]
Could use `vm.SourceTextModule`, perhaps?

**Comment by targos** [comment]
Let's discuss in https://github.com/nodejs/node/issues/36875
