### ISSUE TITLE
No builds for two weeks

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-v8#186]
The last build: https://nodejs.org/download/v8-canary/v16.0.0-v8-canary20201208b712dd932f/ as of 08-Dec-2020.

**Comment by ryzokuken** [comment]
I tried to fix and push a couple of days ago, but it's still broken. Let me investigate.

**Comment by targos** [comment]
I pushed a fix. Running CI: https://ci.nodejs.org/view/MyJobs/job/node-update-v8-canary/1595
