### ISSUE TITLE
WebAssembly Reference Types not functional

### ISSUE THREAD

**Issue by Tarnadas** [nodejs/node-v8#187]
- **Version**: 15.4.0
- **Platform**: Microsoft Windows [Version 10.0.19041.630]
- **Subsystem**: Debian GNU/Linux 10 (buster) - 10.7

Related ticket in the wasm-bindgen repository:
https://github.com/rustwasm/wasm-bindgen/issues/2274

With the latest Nodejs release and also with other Nodejs versions with updated v8 releases from these branches:
https://github.com/targos/node/tree/v8-88
https://github.com/targos/node/tree/v8-87-v15.x
I get an error when trying to run my Rust application compiled to WebAssembly with reference types enabled like this:

```sh
❯ node --experimental-wasm-reftypes .

const wasmModule = new WebAssembly.Module(bytes);
                   ^

CompileError: WebAssembly.Module(): Compiling function #99:"__externref_table_alloc" failed: local.tee[0] expected type i32, found ref.null of type externref @+39165
```

I think this error is related to the modified version of v8 that Nodejs is using, because I can load my WebAssembly module in latest Chrome with v8 8.7.

**Comment by targos** [comment]
Node.js does very few modifications to V8. I think it's more likely that this experimental API requires build option to be enabled or some compiler flag.

**Comment by Tarnadas** [comment]
It seems like the issue came from `wasm-bindgen` and it is now fixed.
