### ISSUE TITLE
"ReferenceError: WebAssembly is not defined" with latest (Jan 26) V8 canary build.

### ISSUE THREAD

**Issue by nolanmar511** [nodejs/node-v8#188]
* **Version**: v16.0.0-v8-canary20210126cca63d5c10 (this issue does not occur with v16.0.0-v8-canary20210125331aeb02a3)
* **Platform**: 5.7.17-1rodete4-amd64 #1 SMP Debian 5.7.17-1rodete4 (2020-10-01) x86_64 GNU/Linux
* **Subsystem**: not sure

### What steps will reproduce the bug?
Compiling and running our [typescript benchmark](https://github.com/google/pprof-nodejs/blob/master/system-test/busybench/src/busybench.ts) fails with "WebAssembly is not defined" while reading source maps.

```
+ node -v
v16.0.0-v8-canary20210126cca63d5c10
+ node --trace-warnings build/src/busybench.js 10
/tmp/tmp.ywAUtcetvv/busybench/node_modules/pprof/out/src/sourcemapper/sourcemapper.js:206
            throw new Error('An error occurred while processing the source map files' + err);
                  ^

Error: An error occurred while processing the source map filesError: An error occurred while reading the sourceMap file /tmp/tmp.ywAUtcetvv/busybench/build/src/busybench.js.map: ReferenceError: WebAssembly is not defined
    at /tmp/tmp.ywAUtcetvv/busybench/node_modules/pprof/out/src/sourcemapper/sourcemapper.js:206:19
    at Generator.throw (<anonymous>)
    at rejected (/tmp/tmp.ywAUtcetvv/busybench/node_modules/pprof/out/src/sourcemapper/sourcemapper.js:21:65)
++ echo '** TEST FAILED **'
+ cd /src/system-test/..
+ npm run clean
** TEST FAILED **
```

### How often does it reproduce? Is there a required condition?
This has reproduced every time we've run our system test with release of the V8 canary build.

### What is the expected behavior?
We'd expect no "ReferenceError: WebAssembly is not defined" error to appear.

### What do you see instead?

"ReferenceError: WebAssembly is not defined" is thrown while processing source maps.

### Additional information

Thanks for maintaining the v8 canary build! Any pointers here would be appreciated.
The latest V8 canary build does seem to have fewer files than the previous (though that could be totally unrelated)

**Comment by nolanmar511** [comment]
Wanted to note that this error persists with v16.0.0-v8-canary202101289af183895a.

Is this type of error now expected?

**Comment by targos** [comment]
I'd say it's not expected, because Chrome Canary doesn't have a problem with WebAssembly as far as I can tell.
I'll check if we need to change something in our build config. There were many commits related to wasm in the last few days: https://github.com/v8/v8/commits/master

**Comment by targos** [comment]
Okay, I found it: https://github.com/v8/v8/commit/27771482715

WebAssembly is now disabled by default in V8. I'm updating the configuration...

**Comment by devsnek** [comment]
> WebAssembly is now disabled by default in V8

fwiw its enabled by default (`v8_enable_webassembly = true`)

**Comment by targos** [comment]
@nolanmar511 can you check today's build?
https://nodejs.org/download/v8-canary/v16.0.0-v8-canary20210129cd2c123f93/

**Comment by nolanmar511** [comment]
Thanks! 
This error went away with the latest V8 canary build.
