### ISSUE TITLE
Last builds lack Windows installers and binaries

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-v8#19]
See
https://nodejs.org/download/v8-canary/v9.0.0-v8-canary201710193971f070e9/
https://nodejs.org/download/v8-canary/v9.0.0-v8-canary201710206d75561466/

The last one with Windows items is
https://nodejs.org/download/v8-canary/v9.0.0-v8-canary20171018c5afbc57bf/

**Comment by targos** [comment]
That's because the build is broken on Windows: https://ci.nodejs.org/job/node-test-commit-windows-fanned/12687/

**Comment by refack** [comment]
Also checking out

**Comment by targos** [comment]
Still failing: https://ci.nodejs.org/job/node-compile-windows/12882/

**Comment by vsemozhetbyt** [comment]
Still lack.
cc @nodejs/platform-windows?

**Comment by seishun** [comment]
CI looks fine, so it's up to @nodejs/build

**Comment by targos** [comment]
CI does not look fine. Here is the last run: https://ci.nodejs.org/job/node-test-commit-windows-fanned/12997/

**Comment by seishun** [comment]
Ah, the dreaded parallel/test-async-wrap-uncaughtexception. See https://github.com/nodejs/node/issues/16210

**Comment by targos** [comment]
Not really. It doesn't even compile.

**Comment by refack** [comment]
It's that json bug. I have a patch for that. I wanted to upstream. I'll float here.

**Comment by targos** [comment]
@refack. Thanks. If you have a working patch, feel free to push a commit on to of [`canary-base`](https://github.com/nodejs/node/commits/canary-base) (in nodejs/node, not this repo). The daily job will pick it up tomorrow.

**Comment by seishun** [comment]
I see here that the last few builds were successful though: https://ci.nodejs.org/job/node-compile-windows/

**Comment by targos** [comment]
We only have one canary build per day (unless it's manually triggered)

**Comment by bzoz** [comment]
https://github.com/nodejs/node/commit/dfcaf280b728b20e536c27964ae1446342d98607 fixed Windows compilation

**Comment by seishun** [comment]
@bzoz we're talking about v8-canary, not master. Took me a while to realize it too.

**Comment by vsemozhetbyt** [comment]
Ping)

**Comment by targos** [comment]
Still many errors with VS2015: https://ci.nodejs.org/job/node-compile-windows/13253/label=win-vs2015/console

**Comment by seishun** [comment]
Confirmed locally, doesn't build with VS2015.

Does V8 have an official supported compilers list? Microsoft may or may not fix the internal compiler error, but they are definitely not going to add relaxed constexpr in VS2015. It's supported since VS2017.

**Comment by refack** [comment]
This is after https://github.com/nodejs/node/commit/5366f807b754461865d5bb84861fed1f5575688c?

**Comment by targos** [comment]
@refack yes

**Comment by refack** [comment]
Breaking CL landed a day ago: https://chromium-review.googlesource.com/c/v8/v8/+/753903

**Comment by hashseed** [comment]
Thanks for pinpointing the culprit. We currently don't have a Windows bot testing Node.js integration on our end, but it looks like we need one. I'll try to get something set up soon.

**Comment by hammacher** [comment]
@hashseed note that this is not about nodejs integration, V8 and chromium are currently not compiled at all with VS2015 AFAICT. So either V8 needs to return to supporting VS2015, or nodejs also switches to VS2017 as proposed in #16868. The latter seems to be the more attractive way forward to me.

**Comment by hashseed** [comment]
What I'm saying is that as long as Node.js has not moved to VS2017, we should have a test bot to build Node.js with VS2015, which would have detected this problem.

It also means that V8 needs to support VS2015 until the switch.

**Comment by hashseed** [comment]
Tracking bug here for those interested https://bugs.chromium.org/p/v8/issues/detail?id=5960

**Comment by joaocgreis** [comment]
Do we need the version of V8 that is failing to land in node v9.x?

Adding a new release machine with VS2017 (ref https://github.com/nodejs/node/issues/13052 and https://github.com/nodejs/node/pull/16868) will fix this.

@hashseed I understand that maintaining VS2015 support is a burden for V8. However, for building native modules, node users must also have VS installed. Asking all node users with VS2015 to update is something that would be good to avoid, some of them might not even be able to. It would be great if V8 could test building node with VS2017 and then testing addons with VS2015, to avoid issues like https://github.com/nodejs/node-v8/issues/4. If this can be done, is there anything I can do to help?

**Comment by seishun** [comment]
>Asking all node users with VS2015 to update is something that would be good to avoid, some of them might not even be able to.

On the other hand, assuming VS2015 is binary incompatible with VS2017, we are currently forcing node users with VS2017 to install VS2015 alongside it, which is arguably worse.

**Comment by joaocgreis** [comment]
>we are currently forcing node users with VS2017 to install VS2015 alongside it

Are we? How? node-gyp should be able to use either and both are supported by us.

**Comment by seishun** [comment]
>node-gyp should be able to use either and both are supported by us.

Well that confirms that VS2015 is binary compatible with VS2017. If they weren't, addons built with VS2017 wouldn't work with node built with VS2015.

**Comment by refack** [comment]
Ignore my last comment. It's about the build issue not the extended constexpr.

**Comment by refack** [comment]
There is the issue of building node core from source, not just addons. Dropping official support for VS2015 is one thing, actually breaking support it is semver-major.

Let's keep that discussion in https://github.com/nodejs/node/pull/16868.

**Comment by targos** [comment]
Do we have a release machine with VS2017?

**Comment by refack** [comment]
@joaocgreis is working on some bugs in vcbuild.bat -
 https://github.com/nodejs/node/pull/17101

**Comment by vsemozhetbyt** [comment]
Is there any progress on this? We still have no Windows binaries.

**Comment by seishun** [comment]
AFAIK @joaocgreis is working on a VS2017 release machine.

**Comment by joaocgreis** [comment]
Release machines ready and working. First node-v8 test run: https://nodejs.org/download/test/v10.0.0-test201711308c5d0f1f35/ . Today's nightlies should already be build by the new machines, if everything goes well this should be fixed.

**Comment by vsemozhetbyt** [comment]
This is fixed! Thank you all!

https://nodejs.org/download/v8-canary/v10.0.0-v8-canary201711307338c21936/
