### ISSUE TITLE
Breaking? change for trace events in V8 9.2

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#200]
It looks like V8 changed some of the trace events it generates. This makes our `test-trace-events-v8` and `test-trace-events-all` tests fail.

In [`the tests`](https://github.com/nodejs/node/blob/87805375645f7af36fce2e59289559f746a7131d/test/parallel/test-trace-events-v8.js#L32), we verify that an event with the name `'V8.ScriptCompiler'` is emitted. With V8 9.2, this is no longer the case. I could replace the check with `'V8.GCScavenger'` to make the test pass again.

/cc @jasnell Do we need to consider this change semver-major? Or can I just adapt the tests?

**Comment by targos** [comment]
I pushed https://github.com/nodejs/node/commit/614efb1bc2042725f847d4161cf8ae126483a7af to fix canary in the mean time.

**Comment by jasnell** [comment]
Trace events in node are still considered experimental so aren't covered by semver.

**Comment by targos** [comment]
Thanks, then I'll close this issue 👍🏻
