### ISSUE TITLE
No builds last 10 days

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-v8#204]
The last build:

https://direct.nodejs.org/download/v8-canary/v17.0.0-v8-canary202107193e60047e23/

**Comment by richardlau** [comment]
Looks like the actions workflow to [update the canary branch](https://github.com/nodejs/node-v8/actions/workflows/update-canary.yml) is broken.
e.g. https://github.com/nodejs/node-v8/runs/3188937642?check_suite_focus=true#step:2:11
```
Error: Input required and not supplied: token
```

**Comment by targos** [comment]
The token was just restored. Releases will probably still fail, though. There is something to adapt in the gyp files that I did not have time to do yet. Anyone feel free to give it a try!

**Comment by targos** [comment]
Here are today's logs: https://github.com/nodejs/node-v8/runs/3199118166?check_suite_focus=true

**Comment by targos** [comment]
It should be fixed now: https://github.com/nodejs/node-v8/actions/runs/1087122489

**Comment by vsemozhetbyt** [comment]
Thank you!
