### ISSUE TITLE
Error during npm install after installing canary

### ISSUE THREAD

**Issue by amchiclet** [nodejs/node-v8#216]
We found some errors while using node-v8 canary.

I've been able to narrow down the steps to reproduce below.

```
$ NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary nvm install v18.0.0-v8-canary2021113060c21743de
$ npm install

npm ERR! Cannot assign to read only property 'name' of function 'class Install extends ArboristWorkspaceCmd {
npm ERR!   static description = 'Install a package'
npm ERR!   static name = 'instal...<omitted>...
npm ERR! }'
```

Let me know if more information is needed or if this is actually a bug against something upstream.

Thank you!

**Comment by richardlau** [comment]
It has been reported upstream https://bugs.chromium.org/p/v8/issues/detail?id=12421
(It came up in Node.js tests https://github.com/nodejs/node/pull/40907#issuecomment-975548270.)

**Comment by amchiclet** [comment]
Ah, thanks so much for the links.

**Comment by targos** [comment]
this is fixed now
