### ISSUE TITLE
Build issue with inspector protocol

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#217]
https://github.com/nodejs/node-v8/runs/4849367189?check_suite_focus=true

```
  ACTION Generating inspector protocol sources from protocol json d23d8a137c8fbb57971473ca20bd47e375edd81c.intermediate
  CXX(target) /home/runner/work/node-v8/node-v8/node-v8/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/default-foreground-task-runner.o
Traceback (most recent call last):
  File "../../deps/v8/third_party/inspector_protocol/code_generator.py", line 702, in <module>
    main()
  File "../../deps/v8/third_party/inspector_protocol/code_generator.py", line 572, in main
    protocol = Protocol(config)
  File "../../deps/v8/third_party/inspector_protocol/code_generator.py", line 360, in __init__
    self.generate_domains = self.read_protocol_file(config.protocol.path)
AttributeError: 'X' object has no attribute 'path'
make[1]: *** [tools/v8_gypfiles/v8_base_without_compiler.target.mk:30: d23d8a137c8fbb57971473ca20bd47e375edd81c.intermediate] Error 1
```

It seems that the `path` property is added from the build file: https://chromium.googlesource.com/v8/v8.git/+/refs/heads/main/src/inspector/BUILD.gn#51

Introduced in https://chromium.googlesource.com/v8/v8.git/+/db77f7fb4acbc7d75fbacbcaed8ded4e36be457f

**Comment by vsemozhetbyt** [comment]
Is this the cause of no canary binaries since [10-Jan-2022](https://direct.nodejs.org/download/v8-canary/v18.0.0-v8-canary20220110228ddfd331/)?

**Comment by targos** [comment]
> Is this the cause of no canary binaries since [10-Jan-2022](https://direct.nodejs.org/download/v8-canary/v18.0.0-v8-canary20220110228ddfd331/)?

Probably.

**Comment by targos** [comment]
I don't know how to handle this correctly on our side, so I'm going to float a patch that adds the field back to inspector_protocol_config.json.

**Comment by targos** [comment]
Actually, I found the solution in the [Bazel file](https://github.com/v8/v8/blob/266f41aa24958b7f65e5c0a57c3b96dfa77e7ce6/BUILD.bazel#L3245) 🎉 
This can easily be done similarly in inspector.gypi: https://github.com/nodejs/node/commit/bcec01e5cca200e7ab2c0ddc10dc189d3be1b414
