### ISSUE TITLE
Latest V8 causing failure in `test-worker-debug`

### ISSUE THREAD

**Issue by codebytere** [nodejs/node-v8#219]
A recent set of V8 commits is causing a failure in `test-worker-debug` here: https://github.com/nodejs/node/blob/master/test/parallel/test-worker-debug.js#L109

owing to this CL: https://chromium-review.googlesource.com/c/v8/v8/+/3345001

which we caught in Electron's latest Chromium update.

I assume the best way forward here is just to remove the assertion, but if there's anything else needed here or work I could help with, please let me know!

**Comment by targos** [comment]
> I assume the best way forward here is just to remove the assertion, but if there's anything else needed here or work I could help with, please let me know!

fwiw that's what the V8 team did in https://github.com/v8/node/pull/135/files

**Comment by codebytere** [comment]
ah cool - thanks!

**Comment by targos** [comment]
I push https://github.com/nodejs/node/commit/4638589b3cd288848ef24dbae0536a1b129adfe0 to canary-base. Thanks for the heads-up!
