### ISSUE TITLE
No canary builds during a month

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-v8#222]
The last build is https://direct.nodejs.org/download/v8-canary/v18.0.0-v8-canary20220323849445f546/

**Comment by targos** [comment]
I don't know why there's nothing in the `v8-canary` folder. Release builds are green. For example yesterday:
https://ci-release.nodejs.org/job/iojs+release/8404/
![image](https://user-images.githubusercontent.com/2352663/164196682-667f4c0b-5d23-48fd-92ac-79b5a1eda5cf.png)

@nodejs/build-infra

**Comment by targos** [comment]
The files are copied to `custom`. That's probably the cause of the problem.

```
13:06:58 scp -p node-v18.0.0-v8-canary20220419dfe2c32b5e-linux-x64.tar.xz node-www:nodejs/custom/v18.0.0-v8-canary20220419dfe2c32b5e/node-v18.0.0-v8-canary20220419dfe2c32b5e-linux-x64.tar.xz
```

**Comment by richardlau** [comment]
> The files are copied to `custom`. That's probably the cause of the problem.
> 
> ```
> 13:06:58 scp -p node-v18.0.0-v8-canary20220419dfe2c32b5e-linux-x64.tar.xz node-www:nodejs/custom/v18.0.0-v8-canary20220419dfe2c32b5e/node-v18.0.0-v8-canary20220419dfe2c32b5e-linux-x64.tar.xz
> ```

Unlikely, that has always been the case -- the builds are staged in `custom` and the promotion script is supposed to be copying the files to `v8-canary` based on the directory name: https://github.com/nodejs/build/blob/5e2ae08283c75eff51de04635883446dce23ad8b/ansible/www-standalone/tools/promote/settings#L16-L18

Given the timings, I think what may have happened is that the test build I was running while adding new release machines for Node.js 18 has caused an issue while promoting `test` builds and making the promotion script bail before promoting `v8-canary` (the order is `nightly`, `next-nightly`, `rc`, `test`, `v8-canary`: 
https://github.com/nodejs/build/blob/371bb7626abe773a56c7c62e76d0a551ba1b9717/ansible/www-standalone/tools/promote/promote_nightly.sh#L14-L43). I'll try to figure out what that is and how to recover.

**Comment by richardlau** [comment]
Running the promotion script as the `dist` user appears to back up that theory -- `v18.0.0-test202202249be1dcff34` was the identifier for the test builds I ran:
```
$ /home/staging/tools/promote/promote_nightly.sh nodejs
Promoting v18.0.0-test202202249be1dcff34/node-v18.0.0-test202202249be1dcff34-linux-arm64.tar.gz...
cp: cannot create regular file '/home/dist/nodejs/test/v18.0.0-test202202249be1dcff34/node-v18.0.0-test202202249be1dcff34-linux-arm64.tar.gz': Permission denied
```

I suspect I've run into https://github.com/nodejs/build/pull/2020 where the destination dist directory intentionally had its permissions changed and I was running builds with the same identifier over more than a five day period. I don't need the `v18.0.0-test202202249be1dcff34` build, so I'll remove the unpromoted assets from staging.

**Comment by richardlau** [comment]
Looks promising:
```
$ /home/staging/tools/promote/promote_nightly.sh nodejs
Promoting v18.0.0-v8-canary20220324863bb10b2d/docs...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-aix-ppc64.tar.gz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-darwin-arm64.tar.gz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-darwin-arm64.tar.xz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-darwin-x64.tar.gz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-darwin-x64.tar.xz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-headers.tar.gz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-headers.tar.xz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-linux-arm64.tar.gz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-linux-arm64.tar.xz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-linux-armv7l.tar.gz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-linux-armv7l.tar.xz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-linux-ppc64le.tar.gz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-linux-ppc64le.tar.xz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-linux-s390x.tar.gz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-linux-s390x.tar.xz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-linux-x64.tar.gz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-linux-x64.tar.xz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d.pkg...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d.tar.gz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d.tar.xz...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-win-x64.7z...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-win-x64.zip...
Promoting v18.0.0-v8-canary20220324863bb10b2d/node-v18.0.0-v8-canary20220324863bb10b2d-x64.msi...
Promoting v18.0.0-v8-canary20220324863bb10b2d/win-x64...
/home/dist/nodejs/v8-canary/v18.0.0-v8-canary20220324863bb10b2d/SHASUMS256.txt
Promoting v18.0.0-v8-canary20220325de62049e54/docs...
...
```

**Comment by richardlau** [comment]
The missing canary builds are all now available.

**Comment by vsemozhetbyt** [comment]
Thank you!
