### ISSUE TITLE
broken test-wasm-simple

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#24]
Probably caused by https://chromium-review.googlesource.com/c/v8/v8/+/775338

**Comment by bmeurer** [comment]
cc @gahaas

**Comment by addaleax** [comment]
Heh, yes. The test for Node was actually suggested by me with this specific feature in mind.

I’m surprised to see V8 extended its platform API to accommodate this – I am pretty sure I had made the preparations for this to work with the old API (i.e. I’m not sure why that extension was necessary).

Anyway, I’m taking a look at the crash itself now.

**Comment by addaleax** [comment]
Fix is in https://github.com/nodejs/node/pull/17134

**Comment by gahaas** [comment]
Hi Anna,

Thanks for addressing this issue so quickly.

Let me quickly explain the reason for the platform API change: There is a fundamental assumption in V8 that the isolate is only used by foreground tasks. The old platform API required the isolate to post new foreground task. In principle this meant that only foreground tasks were able to post new foreground tasks. This was, however insufficient for asynchronous compilation of WebAssembly.

With the new platform API a foreground task can create a TaskRunner using the isolate, and then a background task can use that TaskRunner to post new foreground tasks without using the isolate.

Cheers, Andreas
