### ISSUE TITLE
Build error on Windows (arm64)

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#240]
https://ci.nodejs.org/job/node-compile-windows/46957/nodes=win-vs2019-arm64/console

```
11:13:20   simd.cc
11:13:21 C:\workspace\node-compile-windows\node\deps\v8\src\objects\simd.cc(99,28): error C2078: too many initializers [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
11:13:21 C:\workspace\node-compile-windows\node\deps\v8\src\objects\simd.cc(109,1): error C2766: explicit specialization; 'int v8::internal::`anonymous-namespace'::extract_first_nonzero_index<uint32x4_t>(uint32x4_t)' has already been defined [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
```

**Comment by targos** [comment]
The first error is considered "not a bug" by Microsoft. What should we do?

@nodejs/platform-windows-arm 

https://developercommunity.visualstudio.com/t/error-c2078-too-many-initializers-when-using-arm-n/402911

**Comment by pbo-linaro** [comment]
It seems like a workaround was given by Microsoft (using .128_u8).
It it's working, would that be possible to simply add an ifdef for that compiler (vs gcc/clang)?

**Comment by nsait-linaro** [comment]
We probably should upstream a patch to V8 as well to fix the same issue with MSVC.

**Comment by targos** [comment]
Yes, please send a patch upstream if possible!

**Comment by pbo-linaro** [comment]
I'll look at it :)
If we integrate that in v8, can you easily update to latest version (including current trunk)?

**Comment by targos** [comment]
Yes, the canary branch in this repository is updated automatically every day.

**Comment by pbo-linaro** [comment]
@targos I just submitted [4 patches](https://groups.google.com/g/v8-dev/c/RoYs2mvWPw8/m/mRHKteTNAwAJ) to fix all compilation errors of V8 with MSVC (including some not concerning Node).

This [one](https://chromium-review.googlesource.com/c/v8/v8/+/3913035) solves issue discussed here.

**Comment by targos** [comment]
Amazing!

**Comment by pbo-linaro** [comment]
@targos Patches are now merged upstream, v8 canary should be able to compile for windows from now.

Don't hesitate to ping me if you need help in the future 👍

**Comment by targos** [comment]
Cherry-picked all patches to https://github.com/nodejs/node/pull/44741.
