### ISSUE TITLE
Build error on arm64 Windows

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#247]
https://ci.nodejs.org/job/node-compile-windows/48613/nodes=win-vs2019-arm64/console

```
11:28:48   pointer-auth-arm64.cc
11:28:48 C:\workspace\node-compile-windows\node\deps\v8\src\execution\arm64\pointer-auth-arm64.cc(14,36): error C2370: 'kPACKeyIB': redefinition; different storage class [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_base_without_compiler_host.vcxproj]
11:28:48 C:\workspace\node-compile-windows\node\deps\v8\src\execution\arm64\simulator-arm64.h(1406): message : see declaration of 'kPACKeyIB' [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_base_without_compiler_host.vcxproj]
```

@nodejs/platform-windows-arm

**Comment by pbo-linaro** [comment]
On our side, v8 main branch is building fine, and this file in particular:
https://gitlab.com/Linaro/windowsonarm/nightly/-/jobs/3538610208#L3854

I'll take a look closer next week, but it's probably just a missing ```define``` somewhere.

**Comment by targos** [comment]
I looked at the line where the error occurs and it seems that `USE_SIMULATOR` is defined when it probably shouldn't.

https://github.com/v8/v8/blob/4f7a03ca5bf5d747b4c85af1490b7cfb84f44563/src/execution/arm64/pointer-auth-arm64.cc#LL14C11-L14C11

**Comment by pbo-linaro** [comment]
After investigation, it was not a problem regarding ```USE_SIMULATOR``` define but just a visibility issue. This patch allows to compile this file (you can keep it on node side):

```
diff --git a/deps/v8/src/execution/arm64/pointer-auth-arm64.cc b/deps/v8/src/execution/arm64/pointer-auth-arm64.cc
index 15d80fa978..1bb0a377a9 100644
--- a/deps/v8/src/execution/arm64/pointer-auth-arm64.cc
+++ b/deps/v8/src/execution/arm64/pointer-auth-arm64.cc
@@ -10,7 +10,6 @@ namespace v8 {
 namespace internal {
 
 // Randomly generated example key for simulating only.
-V8_EXPORT_PRIVATE
 const Simulator::PACKey Simulator::kPACKeyIB = {0xeebb163b474e04c8,
                                                 0x5267ac6fc280fb7c, 1};
 

```

**Comment by targos** [comment]
Do we have to keep it on node side?

**Comment by pbo-linaro** [comment]
If I remember well, we already met an issue with V8_EXPORT_PRIVATE not being correctly defined on nodejs, so not sure it's an upstream issue.

**Comment by targos** [comment]
> If I remember well, we already met an issue with V8_EXPORT_PRIVATE not being correctly defined on nodejs side

Do you know how it's defined and how it should be? If you can point me to the place in V8's BUILD.gn that sets it up, I can try to fix our GYP files.

**Comment by pbo-linaro** [comment]
It comes from [here](https://github.com/nodejs/node-v8/blob/f31b3e1c48c1cbe59f380ab9efcd703256097723/deps/v8/src/base/macros.h#L390).

I assume in this precise case, USING_V8_SHARED is defined, while it should be expected that it's not (that was not 100% clear for me last time I looked at nodejs build system).

For now, I can't allocate time to work on this, but the patch mentioned above should not have any other effects than allowing you to compile with latest v8.

**Comment by targos** [comment]
It probably is defined by this line: https://github.com/nodejs/node/blob/a03529d82858ed225f40837f14db71851ad5d885/common.gypi#L392

Added in https://github.com/nodejs/node/commit/4a1efb2b9c02dd5acbf9c0bb3f41267b5acaab11 to "Support native extension loading on Windows".
I don't know if it's still necessary.

**Comment by targos** [comment]
@bnoordhuis maybe you have an idea?

**Comment by bnoordhuis** [comment]
`BUILDING_V8_SHARED` controls both `V8_EXPORT` and `V8_EXPORT_PRIVATE`.

`V8_EXPORT_PRIVATE` is for V8's component build (build as multiple DLLs), which we we don't use, and so we should try to make it evaluate to nothing. May require some hacks to src/base/macros.h.

`V8_EXPORT` affects V8's public API and should stay as-is: `dllexport` when building V8, `dllimport` when building add-ons.

**Comment by targos** [comment]
CI with https://github.com/nodejs/node-v8/commit/691f1c465d74ad6ae7a253fab74af7af98e5611e: https://ci.nodejs.org/job/node-test-commit/58912/

**Comment by targos** [comment]
Seems fixed. Thank you both!
