### ISSUE TITLE
Recent builds do not have Mac .pkg builds

### ISSUE THREAD

**Issue by kriskowal** [nodejs/node-v8#253]
I note that v10 had a `.pkg`.

https://nodejs.org/download/v8-canary/v10.0.0-v8-canary20171101b81802a96b/

And v21 does not appear to have one.

https://nodejs.org/download/v8-canary/v21.0.0-v8-canary20230818e55b32fa00/

I find no issues here mentioning `pkg` or Mac discrepancies, so surfacing this on the off-chance that the `.pkg` is being omitted due to a build failure that’s gone unnoticed.

Apologies if `.pkg` is omitted by design.

**Comment by targos** [comment]
I just opened https://github.com/nodejs/node-v8/issues/263. The mac builds are currently broken because of a recent V8 change.

**Comment by targos** [comment]
.pkg is back: https://nodejs.org/download/v8-canary/v21.0.0-v8-canary20230906bca67b72ce/
