### ISSUE TITLE
Build fails on Windows/MSVC

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#271]
See https://github.com/nodejs/node-v8/actions/runs/6878827246/job/18709360221

It's been happening for some times (several weeks I think). I hoped it would fix itself upstream like it happens sometimes, but unfortunately these errors don't go away.

/cc @nodejs/platform-windows

**Comment by StefanStojanovic** [comment]
I'll take a look at it. Thanks for the info.

**Comment by StefanStojanovic** [comment]
Hey @targos, with these changes in [v8.patch](https://github.com/nodejs/node-v8/files/13449244/v8.patch) I was able to build Node.js. I know there is a GHA for building on Windows, but I'm not sure if there is a way to run tests on Windows through this repo (I couldn't find it). In any case, we can always use the CI for that. Since I'm new to this repo, can you try applying this patch and running it through GHA, or explain to me how to do it?

A few details on the problem - there were two problematic commits in V8 I found: https://github.com/v8/v8/commit/cb9bdcf313ee57338a520cceaa8901ef004fbf6b and https://github.com/v8/v8/commit/8005bd282bf1565a11cae24a9811e99f8b3fc64b. I did partial reverts of them as they were refactoring some parts of code that were problematic when building. The biggest issue was changing the `typename` in templates and exposing them via `using`. My patch file keeps commit history (2 reverts and 1 hotfix I had to apply after), but can ultimately be squashed if we decide to use it in future V8 updates.

**Comment by targos** [comment]
> In any case, we can always use the CI for that.

That's probably the best thing to do. I guess we can apply the patch temporarily if needed, but the goal should be to send changes upstream. I doubt that the would accept 2 reverts?

**Comment by targos** [comment]
@StefanStojanovic V8 update PR: https://github.com/nodejs/node/pull/51362

**Comment by medjamac** [comment]
| Team Name | App Description | Programming Language/Framework | [demo](https://github.com/pi-apps/demo) | app-name.PiNet.com link if applicable |

**Comment by rbuckton** [comment]
Are v8-canary builds for Windows still broken? I've been using a build from last September to test out the V8 dev trial for the [Shared Structs proposal](https://github.com/tc39/proposal-structs), but haven't been able to use any of the more recent versions as they are lacking windows builds.

**Comment by targos** [comment]
Yes, they're still broken, and the fix from https://github.com/nodejs/node/pull/51362/commits/6f6a7fc5d02c76ac85a12e43ad6ce126d35283ca doesn't apply cleanly to V8's lkgr branch.

**Comment by vsemozhetbyt** [comment]
As this issue is closed, are there any other issues that still prevent Windows canary builds in https://direct.nodejs.org/download/v8-canary/ ?

**Comment by targos** [comment]
I'll check tomorrow

**Comment by targos** [comment]
Still fails, but now for a different reason:

https://ci-release.nodejs.org/job/iojs+release/10154/nodes=vs2022-x64/console

```
12:35:17      Creating library out\Release\node_mksnapshot.lib and object out\Release\node_mksnapshot.exp
12:35:21      Creating library out\Release\cctest.lib and object out\Release\cctest.exp
12:35:23   node_mksnapshot.vcxproj -> out\Release\\node_mksnapshot.exe
12:35:23   node_mksnapshot
12:35:25   
12:35:25   
12:35:25   #
12:35:25   # Fatal error in , line 0
12:35:25   # Check failed: table->address(index) == table->address(encoded_index).
12:35:25   #
12:35:25   #
12:35:25   #
12:35:25   #FailureMessage Object: 00000095E5AFE950
12:35:25   ----- Native stack trace -----
12:35:25   
12:35:26    1: 00007FF7C11A86BB node::DumpNativeBacktrace+155 [c:\ws\src\debug_utils.cc]:L313
12:35:26    2: 00007FF7C123D4CF `node::NodePlatform::GetStackTracePrinter'::`2'::<lambda_1>::<lambda_invoker_cdecl>+47 [c:\ws\src\node_platform.cc]:L583
12:35:26    3: 00007FF7C2729F65 V8_Fatal+197 [c:\ws\deps\v8\src\base\logging.cc]:L204
12:35:26    4: 00007FF7C2045AE0 v8::internal::StartupDeserializer::DeserializeAndCheckExternalReferenceTable+368 [c:\ws\deps\v8\src\snapshot\startup-deserializer.cc]:L103
12:35:26    5: 00007FF7C2045D55 v8::internal::StartupDeserializer::DeserializeIntoIsolate+533 [c:\ws\deps\v8\src\snapshot\startup-deserializer.cc]:L41
12:35:26    6: 00007FF7C1A7BDA8 v8::internal::Isolate::Init+3800 [c:\ws\deps\v8\src\execution\isolate.cc]:L5197
12:35:26    7: 00007FF7C1B53852 v8::internal::Snapshot::Initialize+450 [c:\ws\deps\v8\src\snapshot\snapshot.cc]:L198
12:35:26    8: 00007FF7C1B53405 v8::internal::SnapshotCreatorImpl::InitInternal+69 [c:\ws\deps\v8\src\snapshot\snapshot.cc]:L869
12:35:26    9: 00007FF7C1B4FF99 v8::internal::SnapshotCreatorImpl::SnapshotCreatorImpl+121 [c:\ws\deps\v8\src\snapshot\snapshot.cc]:L895
12:35:26   10: 00007FF7C18ED02B v8::SnapshotCreator::SnapshotCreator+75 [c:\ws\deps\v8\src\api\api.cc]:L543
12:35:26   11: 00007FF7C129CFAB node::CommonEnvironmentSetup::CommonEnvironmentSetup+459 [c:\ws\src\api\embed_helpers.cc]:L135
12:35:26   12: 00007FF7C129DF0C node::CommonEnvironmentSetup::CreateForSnapshotting+188 [c:\ws\src\api\embed_helpers.cc]:L201
12:35:26   13: 00007FF7C1179245 node::BuildSnapshotWithoutCodeCache+101 [c:\ws\src\node_snapshotable.cc]:L979
12:35:26   14: 00007FF7C117C26D node::SnapshotBuilder::GenerateAsSource+813 [c:\ws\src\node_snapshotable.cc]:L1226
12:35:26   15: 00007FF7C0DE7E83 BuildSnapshot+899 [c:\ws\tools\snapshot\node_mksnapshot.cc]:L96
12:35:26   16: 00007FF7C3214DA4 __scrt_common_main_seh+268 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl]:L288
12:35:26   17: 00007FFCAC8E4CB0 BaseThreadInitThunk+16
12:35:26   18: 00007FFCAD27E8AB RtlUserThreadStart+43
12:35:26 C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5): error MSB8066: Custom build for 'out\Release\\node_mksnapshot.exe;deps\openssl\nodejs-openssl.cnf' exited with code -2147483645. [c:\ws\node.vcxproj]
```

**Comment by targos** [comment]
@joyeecheung does that ring a bell?

**Comment by targos** [comment]
It's https://github.com/v8/v8/commit/f4e06442848677b3f9fae50495f7fe0f3d8f0c20

Needs a gyp variant of https://github.com/v8/node/pull/176

**Comment by targos** [comment]
I pushed https://github.com/nodejs/node-v8/commit/47d38753d1d5ffd1e481e931088f626f862ae8c2 🤞🏻

**Comment by targos** [comment]
Added https://github.com/nodejs/node-v8/commit/dbf8f5d8d5041a1c12bc1a24ae962ee5f0f8cb2a to fix another issue.

**Comment by targos** [comment]
It broke everything. I found another way to make it right: https://github.com/nodejs/node-v8/commit/bf2905726eab2409da70af57a6f787823f0a2f06

**Comment by targos** [comment]
CI: https://ci.nodejs.org/job/node-test-commit/70322/

**Comment by targos** [comment]
Finally :sob:
