### ISSUE TITLE
Incredibly Unsafe to Release with v8

### ISSUE THREAD

**Issue by hteslol** [nodejs/node-v8#278]
I have been doing some research, and with we Web Assembly in Chromium I am able to to use prototype's to rewrite standard JavaScript functions, and reach sensitive chrome/system memory - 

https://stackoverflow.com/questions/25755516/get-prototype-from-a-constructor-without-creating-an-instance-in-v8

**This also works with taking NodeJS libraries and doing the same thing.**

**Comment by targos** [comment]
This is not the right place to open an issue if you found a vulnerability in V8.

**Comment by hteslol** [comment]
This is where the website lead me - I agree, but chromium doesn't hire anyone so I don't know who works on it - but you know what I mean... 

I suppose it's something difficult to bake into everything but back to 2006 JS/Node/Chromium/Google are taking as it seems - we don't need the front-end to do the business logic... use a **backend**.
