### ISSUE TITLE
Missing constants for postmortem metadata

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#33]
CI run: https://ci.nodejs.org/job/node-test-commit-node-v8/252/

Missing constants:
* v8dbg_bit_field3_dictionary_map_shift
* v8dbg_class_Map__inobject_properties_or_constructor_function_index__int
* v8dbg_class_Map__instance_attributes__int
* v8dbg_class_Map__instance_size__int

/cc @nodejs/post-mortem

**Comment by cjihrig** [comment]
PR coming up

**Comment by cjihrig** [comment]
Fix in https://github.com/nodejs/node-v8/pull/34
