### ISSUE TITLE
Upcoming change to build config

### ISSUE THREAD

**Issue by hashseed** [nodejs/node-v8#39]
This [upcoming change](https://chromium-review.googlesource.com/c/v8/v8/+/946011) will change the `run_mksnapshot` build target to produce one more file. The background is that we want to make builtin code objects isolate-independent and move them off V8's heap and embed them in the binary instead.

I don't think this will cause breakages in the short term, since this configuration is gated by a build flag. It makes sense to look out for this and maybe port to gyp though.

**Comment by targos** [comment]
For reference, commits that landed:
https://github.com/v8/v8/commit/e6476f89307c516c22d5c87875925f53edf6b58e
https://github.com/v8/v8/commit/f45eca794c3e8da46e9f16fe9618eb29af4cd052

**Comment by targos** [comment]
Also: https://github.com/v8/v8/commit/abcc28ced071faee637d5fd59d06cfdf80d8ea3f

**Comment by refack** [comment]
@targos this still hasn't been done, right? I'll fold this into https://github.com/refack/node/tree/gyp-v8-embedded-builtins

**Comment by targos** [comment]
This hasn't been done

**Comment by targos** [comment]
Done in https://github.com/nodejs/node/pull/22920
