### ISSUE TITLE
what's the usage of 'T ___coalition' in v8 profile log

### ISSUE THREAD

**Issue by code-tinker** [nodejs/node-v8#41]
I am using v8 profiler to optimize my code. And I got this:
![_a760e796-7858-4bf4-aa5f-a9e37c642452](https://user-images.githubusercontent.com/3404780/37277567-0e72502c-2620-11e8-8696-fb85b608cd44.png)

What's the usage of 'T __coalition' and why it occupies so many ticks.
🙏🙏🙏Thanks for watching

**Comment by hashseed** [comment]
What operating system are you running this on?

**Comment by ebraminio** [comment]
I guess macOS, as the directories naming.

**Comment by hashseed** [comment]
Maybe you are making tons of sys calls. See https://opensource.apple.com/source/xnu/xnu-3789.21.4/bsd/sys/coalition.h.auto.html

**Comment by code-tinker** [comment]
@hashseed 
tks u so much !!!
