### ISSUE TITLE
"High-resolution TimeTicks are not available on this system."

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-v8#51]
I have two machines with Windows 7 SP 1 x64 with a similar soft environment (I can build common node on both).

When I run the last nightly (`10.0.0-nightly2018040653aaa55a3a` with V8 `6.5.254.43-node.5`) on both, no warnings appear.

When I run the last v8-canary (`10.0.0-v8-canary20180405bbeda20b90` with V8 `6.7.227-node.0`) on both, one launch does not cause any warnings, another one emit this warning:

```sh
WARNING: High-resolution TimeTicks are not available on this system.
```

What is the possible cause of this in Node.js and on the OS?

**Comment by targos** [comment]
Refs: https://bugs.chromium.org/p/v8/issues/detail?id=7617

Fixed by @MylesBorins in https://github.com/v8/v8/commit/9ca75fb6352ae2e18aa6dd3f7d55b3330ce82574

**Comment by vsemozhetbyt** [comment]
Thank you! I this a hardware or software issue?
