### ISSUE TITLE
Form data

### ISSUE THREAD

**Issue by timusiiit123** [nodejs/node-v8#52]
Hello,

I have made my own API without using express or in core NodeJS. I have an error when I post form data by Postman tool but when I try from raw-data it works what I need.

Error: **SyntaxError: Unexpected token u in JSON at position 1**

**Comment by apapirovski** [comment]
I think you would be more likely to get help in https://github.com/nodejs/help/issues — this tracker is for `node-v8` issues only, not general help. Also if you do post in the help repo, most people would likely need a bit more info to help out. For example some actual code from the project or a more detailed description of what you're doing.
