### ISSUE TITLE
Torque

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#53]
Since https://chromium-review.googlesource.com/c/v8/v8/+/845682 landed upstream, we can no longer build V8 with gyp.

I suppose we will have to port `run_torque` from GN to GYP.

@nodejs/gyp 
@nodejs/v8-update

**Comment by bnoordhuis** [comment]
I can do that if there are no volunteers.

**Comment by targos** [comment]
I'm not able to do it myself.

Whoever does that can base their work off this branch: https://github.com/nodejs/node/commits/canary-base

**Comment by bnoordhuis** [comment]
The PR should still be against this repo, right?

**Comment by targos** [comment]
Yes. I updated the canary branch so you can open a PR against it.

**Comment by devsnek** [comment]
why can't we just update node to gn at this point

**Comment by gibfahn** [comment]
@devsnek that is being discussed in a different issue (which I can't find right now), but the net is that porting V8 is quite straightforward, but porting other node dependencies will be much harder.

So if we're going to change (which I think most people think we should) we should make sure we pick the thing that's going to be easiest to maintain in the long term.

**Comment by bnoordhuis** [comment]
#54 - torque, torque, torque, eat soup with a...?

**Comment by hashseed** [comment]
Info on gyp/gn: https://docs.google.com/document/d/1gvHuesiuvLzD6X6ONddxXRxhODlOJlxgfoTNZTlKLGA/edit?usp=drivesdk

**Comment by vsemozhetbyt** [comment]
Is there any ETA for canary build renewal?

**Comment by targos** [comment]
When https://github.com/nodejs/node-v8/pull/54 is resolved. I think no-one looked into the windows error yet

**Comment by targos** [comment]
Initial gyp implementation landed from https://github.com/nodejs/node-v8/pull/54. There should be a new canary build tomorrow.
