### ISSUE TITLE
AIX build failure 

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#55]
CI run: https://ci.nodejs.org/job/node-test-commit-aix/14644/nodes=aix61-ppc64/console

Error:

```
ld: 0711-317 ERROR: Undefined symbol: .std::condition_variable::wait(std::unique_lock<std::mutex>&)
ld: 0711-317 ERROR: Undefined symbol: .std::condition_variable::notify_one()
ld: 0711-317 ERROR: Undefined symbol: .std::condition_variable::notify_all()
ld: 0711-317 ERROR: Undefined symbol: .std::condition_variable::condition_variable()
ld: 0711-317 ERROR: Undefined symbol: .std::condition_variable::~condition_variable()
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
collect2: error: ld returned 8 exit status
gmake[2]: *** [/home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/out/Release/torque] Error 1
```

/cc @nodejs/platform-aix

**Comment by mhdawson** [comment]
@john-yan @jBarz

**Comment by jBarz** [comment]
looking into it

**Comment by jBarz** [comment]
fyi, I am able to build the `canary-base` branch on my local aix machine using gcc 6.3.0.

**Comment by mhdawson** [comment]
We have updated the compiler to resolve that issue.  

Running on nodejs/node-v8, refs/heads/canary

```
{anonymous}::AdaptorWithExitFrameType(v8::internal::MacroAssembler*, v8::internal::Builtins::ExitFrameType)':
../deps/v8/src/builtins/ppc/builtins-ppc.cc:70:3: error: 'CEntryStub' was not declared in this scope
   CEntryStub stub(masm->isolate(), 1, kDontSaveFPRegs, kArgvOnStack,
   ^~~~~~~~~~
../deps/v8/src/builtins/ppc/builtins-ppc.cc:72:15: error: 'stub' was not declared in this scope
   __ Jump(stub.GetCode(), RelocInfo::CODE_TARGET);
               ^~~~
```

but that looks related to https://github.com/nodejs/node-v8/pull/58 @bnoordhuis as opposed to the error reported here.  @bnoordhuis 

@jBarz you had mentioned that you had gotten it to compile ok before so I could be wrong about it being related to what @bnoordhuis is working on can you check with @john-yan to see if its something that needs a port on our side or not.

**Comment by mhdawson** [comment]
Thinking about it I'm guess I'm most likely wrong and its more likely that we may not be up to date.  In any case @jBarz and @john-yan can you figure that out.

**Comment by targos** [comment]
Today's canary build looks good on AIX, thanks!

https://ci.nodejs.org/job/node-test-commit-node-v8/32/

Do we need to update the requirements in https://github.com/nodejs/node/blob/master/BUILDING.md#aix or GCC 6.3 is good enough?

**Comment by mhdawson** [comment]
@targos its still GCC 6.3, our previous install (bit of a long story) ended up having missed some files due to absolute symlinks that did not match were it is installed on the community machines.  We've fixed that.

**Comment by targos** [comment]
Okay, this can be closed then!
