### ISSUE TITLE
please update the readme to avoid confusion

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/node-v8#6]
Someone I know was somewhat confused if this was the main node repo or not, we should probably either patch the readme, or be much more clear in the repo name + description.

**Comment by bnb** [comment]
+1 - is it possible to get an update on this?

**Comment by tniessen** [comment]
I would suggest to update the description - e.g. `Node.js mirror on ...` instead of `Node.js on ...`.

**Comment by targos** [comment]
Updated in https://github.com/nodejs/node-v8/pull/13

To change the contents of the new README, one can open a PR against the [`readme`](https://github.com/nodejs/node-v8/tree/readme) branch.

**Comment by targos** [comment]
I also changed the description to "Experimental Node.js mirror on V8 Tip-of-Tree"
