### ISSUE TITLE
CallOnBackgroundThread removed from v8-platform

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#62]
See:
https://chromium-review.googlesource.com/c/v8/v8/+/942823
https://chromium-review.googlesource.com/c/v8/v8/+/941944
https://chromium-review.googlesource.com/c/v8/v8/+/1045310

/cc @nodejs/v8-update @addaleax

**Comment by targos** [comment]
Checkout https://github.com/nodejs/node/tree/canary-base for a branch without the API.

**Comment by addaleax** [comment]
I think https://github.com/v8/node/pull/69 is what we want for this?

**Comment by targos** [comment]
Right, that fixes it. Thanks!
