### ISSUE TITLE
Port torque_base to gyp

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#74]
https://github.com/v8/v8/commit/f31c6419ebd6362225fb1838d7ccbcae7bddeda4#diff-4eaebbcd1dc0da11e3a3ce488290bfc6

We'll need it to run V8 tests.

**Comment by targos** [comment]
It doesn't seem necessary. `make test-v8` passes already.

**Comment by refack** [comment]
AFAICT it's because the `torque` target covers these files, but we could replicate the refactoring.
https://github.com/nodejs/node-v8/blob/a7defddf340e425d68d3f54d7b583295e6c86d67/deps/v8/gypfiles/v8.gyp#L2606-L2633

**Comment by refack** [comment]
I did that as part of the `builtins` patch.

**Comment by targos** [comment]
Done in https://github.com/nodejs/node/pull/22920
