### ISSUE TITLE
failing test-trace-events-dynamic-enable

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#78]
This test was added in https://github.com/nodejs/node/pull/22114

That PR backported https://chromium-review.googlesource.com/1161518 from V8.

The problem is that the CL was reverted in https://chromium-review.googlesource.com/1162122 and never relanded.

/cc @ofrobots 

```
=== release test-trace-events-dynamic-enable ===
Path: parallel/test-trace-events-dynamic-enable
/home/mzasso/git/nodejs/canary/test/common/index.js:760
const crashOnUnhandledRejection = (err) => { throw err; };
                                             ^

AssertionError [ERR_ASSERTION]: Expected inputs to be strictly equal:

0 !== 1

    at test (/home/mzasso/git/nodejs/canary/test/parallel/test-trace-events-dynamic-enable.js:54:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:270:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:745:3)
Command: out/Release/node /home/mzasso/git/nodejs/canary/test/parallel/test-trace-events-dynamic-enable.js
```

**Comment by ofrobots** [comment]
I'll take a look. I am working on relanding the original change upstream. I had to fix some thread-safety issues (unrelated to the nodejs/node#22114, but exposed by it) that caused the revert. The upstream fixes that have landed: https://github.com/v8/v8/commit/602aeb4, and https://github.com/v8/v8/commit/f964846. I am still working on the reland: https://chromium-review.googlesource.com/c/v8/v8/+/1188529

**Comment by targos** [comment]
Any progress? I see there was some trouble with the reland CL

**Comment by ofrobots** [comment]
@targos I'm looking at this now.

**Comment by ofrobots** [comment]
The ASAN issues in V8 CQ were legitimate, and should be fixed by this fix: https://chromium-review.googlesource.com/c/v8/v8/+/1228419. Here are the steps that need to happen:

1. Land the above mentioned fix.
1. Rebase https://chromium-review.googlesource.com/c/v8/v8/+/1188529 on top of the fix. It should land cleanly this time.
1. Pick up all these patches here.

Until then, we can either revert the change that introduced the test in Node, or disable it, like you have already. I'll let you decide on the approach.

**Comment by ofrobots** [comment]
Both changes have landed upstream.

**Comment by targos** [comment]
Nice! Can we try to have the changes backported upstream?

**Comment by targos** [comment]
LMK if I should open an issue for the merge request

**Comment by targos** [comment]
Merge request opened: https://bugs.chromium.org/p/v8/issues/detail?id=8199
