### ISSUE TITLE
Broken V8 test

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#83]
https://ci.nodejs.org/job/node-test-commit-v8-linux/1735/

https://ci.nodejs.org/job/node-test-commit-v8-linux/1735/nodes=benchmark,v8test=v8test/testReport/junit/(root)/v8tests/mjsunit_wasm_jsapi_harness/

**Comment by targos** [comment]
It's because we need to fetch `v8/test/wasm-js`. The following patch fixes it:

```patch
diff --git a/deps/v8/tools/node/fetch_deps.py b/deps/v8/tools/node/fetch_deps.py
index 7f34bb4179..332c6e2d7d 100755
--- a/deps/v8/tools/node/fetch_deps.py
+++ b/deps/v8/tools/node/fetch_deps.py
@@ -32,7 +32,6 @@ GCLIENT_SOLUTION = [
       "v8/test/mozilla/data"                  : None,
       "v8/test/test262/data"                  : None,
       "v8/test/test262/harness"               : None,
-      "v8/test/wasm-js"                       : None,
       "v8/third_party/android_ndk"            : None,
       "v8/third_party/android_tools"          : None,
       "v8/third_party/catapult"               : None,
```

@hashseed what do you think?

**Comment by hashseed** [comment]
Do you run V8 tests relying on `fetch_deps.py`. It's originally intended for building node with `--build-v8-with-gn`, which doesn't depend on tests.

We could either go with your patch, or not run wasm tests at all. I'm fine with either.

**Comment by targos** [comment]
Yes, we currently do this:

- Run https://github.com/nodejs/node-v8/blob/canary/tools/make-v8.sh to build V8
- Run V8 tests: https://github.com/nodejs/node-v8/blob/ac272b331988306812c2d3e8ddb022c0b3eed472/Makefile#L570-L576

Maybe there's a better way?

**Comment by hashseed** [comment]
Does TAP_V8 include wasm tests?

**Comment by targos** [comment]
No, it just contains the `--junitout` config flag.
But the test that's failing is in `mjsunit` directory: https://github.com/nodejs/node-v8/blob/ac272b331988306812c2d3e8ddb022c0b3eed472/deps/v8/test/mjsunit/wasm/jsapi-harness.js#L102-L104

**Comment by targos** [comment]
Maybe that's actually a bug in the test? The 3 files are present in `mjsunit/wasm` so it doesn't seem necessary to load them from another place.

**Comment by hashseed** [comment]
I think that the tests are ok. Wasm test suite is shared between implementations, but it includes utilities that are reused here.

I would be fine with changing `fetch_deps.py`. You could also add a new flag to indicate what we are fetching deps for, so that we don't need to fetch wasm tests for building V8.

**Comment by targos** [comment]
I created https://chromium-review.googlesource.com/c/v8/v8/+/1278166

**Comment by targos** [comment]
Change landed upstream. I'll open a merge request for 7.1
