### ISSUE TITLE
Failures with V8 (de)serialization

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#87]
Can be reproduced with the latest canary-base: https://github.com/nodejs/node/commits/canary-base

/cc @addaleax 

```
=== release test-v8-deserialize-buffer ===
Path: parallel/test-v8-deserialize-buffer
#
# Fatal error in , line 0
# Check failed: AllowJavascriptExecution::IsAllowed(isolate).
#
#
#
#FailureMessage Object: 0x7ffd16a323d0
Command: out/Release/node --pending-deprecation --no-warnings /home/mzasso/git/nodejs/canary/test/parallel/test-v8-deserialize-buffer.js
--- CRASHED (Signal: 4) ---
=== release test-v8-serdes ===
Path: parallel/test-v8-serdes
#
# Fatal error in , line 0
# Check failed: AllowJavascriptExecution::IsAllowed(isolate).
#
#
#
#FailureMessage Object: 0x7ffed8069ce0
Command: out/Release/node --expose-gc --expose-internals /home/mzasso/git/nodejs/canary/test/parallel/test-v8-serdes.js
--- CRASHED (Signal: 4) ---
```

**Comment by targos** [comment]
Small repro:

```js
// Flags: --expose-internals
'use strict';
const v8 = require('v8');
const value = Uint8Array.of(1, 2, 3);
const ser = new v8.DefaultSerializer();
ser.writeHeader();
ser.writeValue(value);
const des = new v8.DefaultDeserializer(ser.releaseBuffer());
des.readHeader();
des.readValue();
```

**Comment by targos** [comment]
Probably caused by https://chromium-review.googlesource.com/c/v8/v8/+/1339699

/cc @hashseed

**Comment by hashseed** [comment]
I already landed a fix to vee-eight-lkgr for this.

**Comment by hashseed** [comment]
See 72e90edc20f2f0a05d77f278ac8649acc4991a8a

**Comment by hashseed** [comment]
See https://github.com/v8/node/commit/72e90edc20f2f0a05d77f278ac8649acc4991a8a

**Comment by targos** [comment]
@hashseed ah, thanks! I watch that repo but GH doesn't send notifications for commits (which is a good thing, of course. But I missed the change).

**Comment by targos** [comment]
I cherry-picked the commit

**Comment by addaleax** [comment]
@hashseed Is this, like, the best solution to this issue? I’m just wondering, because I wouldn’t expect V8 to forbid JS execution unless there’s a technical reason to do so?

**Comment by hashseed** [comment]
Executing arbitrary JS during deserialization is not intended because objects may not be fully initialized yet. While it's not a big issue for Node.js, it could cause breakage in Chrome due to the latter running untrusted JS.
