### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#98]
See https://ci.nodejs.org/job/node-compile-windows/23577/label=win-vs2017/console

**Comment by bzoz** [comment]
Those look like something is off with the source code:
```
c:\workspace\node-compile-windows\deps\v8\src/wasm/wasm-limits.h(51): error C2589: '(': illegal token on right side of '::' (compiling source file ..\src\trap-handler\handler-inside-win.cc) [c:\workspace\node-compile-windows\deps\v8\gypfiles\v8_base_2.vcxproj]
```

**Comment by refack** [comment]
Attempt at fixing https://github.com/nodejs/node/pull/25393.
If this works, I'll upstream.

**Comment by targos** [comment]
Was it fixed upstream? Or is this issue shadowed by https://github.com/nodejs/node-v8/issues/94#issuecomment-455844564?

**Comment by dcodeIO** [comment]
Would also appreciate Windows builds again :)

**Comment by vsemozhetbyt** [comment]
Last build has binaries for Windows: https://nodejs.org/download/v8-canary/v12.0.0-v8-canary20190317da0952ae7d/
